"""add tracking fields to User table

Revision ID: 47071d2099ff
Revises: 3e5174d08032
Create Date: 2024-11-30 01:49:46.018502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47071d2099ff'
down_revision = '3e5174d08032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('current_login_at')

    # ### end Alembic commands ###
